# Generated by Django 2.2 on 2019-04-05 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ekipa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kratica', models.CharField(help_text='Kratica ekipe', max_length=200)),
                ('trener', models.CharField(help_text='Trener ekipe', max_length=200)),
                ('ime', models.CharField(help_text='Polno ime ekipe', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Ekipe',
            },
        ),
        migrations.CreateModel(
            name='Igralec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stevilka', models.PositiveSmallIntegerField(help_text='Številka dresa igralca')),
                ('ime', models.CharField(help_text='Ime igralca', max_length=200)),
                ('pozicija', models.CharField(choices=[('PG', 'Playmaker'), ('SG', 'Small Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], help_text='Pozicija igralca', max_length=200)),
                ('teza', models.PositiveSmallIntegerField(help_text='Teza igralca')),
                ('visina', models.PositiveSmallIntegerField(help_text='Višina igralca')),
                ('letoRojstva', models.PositiveSmallIntegerField(help_text='Leto rojstva igralca')),
            ],
            options={
                'verbose_name_plural': 'Igralci',
            },
        ),
        migrations.CreateModel(
            name='Tekma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(help_text='Datum tekme')),
                ('tockeEkipa', models.PositiveIntegerField(help_text='Točke ekipe')),
                ('tockeNasportne', models.PositiveIntegerField(help_text='Točke nasportnika')),
                ('ekipa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tekma_ekipa', to='miami.Ekipa')),
                ('nasprotnik', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tekma_nasprotnik', to='miami.Ekipa')),
            ],
            options={
                'verbose_name_plural': 'Tekme',
            },
        ),
        migrations.CreateModel(
            name='Statistika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skoki', models.PositiveIntegerField(help_text='Skoki igralca')),
                ('podaje', models.PositiveIntegerField(help_text='Podaje igralca')),
                ('ukradene', models.PositiveIntegerField(help_text='Ukradene žoge igralca')),
                ('tocke', models.PositiveIntegerField(help_text='Točke igralca')),
                ('igralec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistika_igralec', to='miami.Igralec')),
                ('tekma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistika_tekma', to='miami.Tekma')),
            ],
            options={
                'verbose_name_plural': 'Statistike',
            },
        ),
    ]
