# Generated by Django 2.2 on 2019-04-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miami', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tekma',
            name='ekipa',
        ),
    ]
