# Generated by Django 2.0.9 on 2019-04-11 07:10

from django.db import migrations
import csv


def napolni_bazo(apps, schema_editor):



class Migration(migrations.Migration):

    dependencies = [
        ('miami', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(napolni_bazo),
    ]
