# Generated by Django 2.2 on 2019-05-06 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miami', '0002_napolni_bazo_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igralec',
            name='slika',
            field=models.ImageField(default='media/igralci/missing.jpg', upload_to='igralci/'),
        ),
    ]
