# Generated by Django 2.1.5 on 2019-04-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miami', '0002_napolni_bazo_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clanstvo',
        ),
    ]
