# Generated by Django 2.1.5 on 2019-05-30 06:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miami', '0002_napolni_bazo_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='igralec',
            name='do',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='igralec',
            name='od',
            field=models.DateField(default=datetime.date(2017, 10, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='igralec',
            name='slika',
            field=models.ImageField(default='igralci/missing.jpg', upload_to='igralci/'),
        ),
    ]
