# Generated by Django 2.2 on 2019-05-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miami', '0003_auto_20190506_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igralec',
            name='slika',
            field=models.ImageField(default='/media/igralci/missing.jpg', upload_to='igralci/'),
        ),
    ]
