# Generated by Django 2.2 on 2019-05-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miami', '0004_auto_20190506_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igralec',
            name='slika',
            field=models.ImageField(default='media/igralci/missing.jpg', upload_to='media/igralci/'),
        ),
    ]
